services:
  - type: web
    name: GAME_ID-nakama
    runtime: docker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: GAME_ID-db
          property: connectionString

databases:
  - name: GAME_ID-db
    databaseName: nakama
