services:
  - type: web
    name: GAME_ID-nakama
    runtime: docker
    envVars:
      - key: GAME_ID
        value: GAME_ID
      - key: PLATFORM_IDENTITY_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: GAME_ID-db
          property: connectionString

databases:
  - name: GAME_ID-db
    databaseName: nakama
